# Generated by Django 5.1.6 on 2025-02-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ci',
            field=models.TextField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.TextField(max_length=45, unique=True),
        ),
    ]
